language: node_js
node_js:
  - "6.1"

sudo: required

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm install karma-phantomjs-launcher --save-dev

script:
  - npm test
